version: "3"

services:
  php-fpm:
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - "${NGINX_PORT}:80"
